### ISSUE TITLE
ESP8266 is not showing as a member on FTS Server

### ISSUE THREAD

**Issue by DanielHeinze** [Cale-Torino/FreeTAKServer_ESP8266_Sensor#1]
i have succesfull connected to wifi and fts server and the steps below are working. 
the ESP is sending the COT every 10 secends.
But i cant see the device in the member list and cant send commands to the device like "Roger" and "callRESET"

Step 1

The device connects via long TCP connection and sends a ping COT [t-x-c-t].

Step 2

Then after 10s it sends an update COT [a-f-G-U-C-I].

Step 3

Then for every 8 ping COTS 1 update COT will be sent in a loop as long as the TCP connection is active.

**Comment by Cale-Torino** [comment]
It should show the device on the `lat="0.00000000" lon="0.00000000"` but can't update since there is no GPS module.

What version of FTS and what version of the sketch are you using? in `ESP8266_TAK_v1.0.0.3.ino` I have a `callRESTART` but don't have a `callRESET` function.

Check out the `static void replyToServer(void* arg)` method and the `static void handleData(void* arg, AsyncClient* client, void *data, size_t len)` method.

let me know if you still have an issue.

**Comment by DanielHeinze** [comment]
Hi, thanks for the trobleshooting. Iam using FTS 1.9.9 maybe there is a problem with sending CoT at the moment?
Using the v1.0.0.3 sketch

the device is not in the map tried to find it with wintak client and civ android.

**Comment by DanielHeinze** [comment]
I checked the `static void replyToServer(void* arg)` method and changed all four lines to this 


`sprintf(message, "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><event version=\"2.0\" uid=\"S-1-5-21-1568504889-667903775-1938598950-%d\" type=\"a-f-G-U-C-I\" time=\"%s\" start=\"%s\" stale=\"%s\" how=\"h-g-i-g-o\"><point lat=\"0\" lon=\"0\" hae=\"0\" ce=\"9999999\" le=\"9999999\"/><detail><takv version=\"4.1.0.231\" platform=\"WinTAK-CIV\" os=\"ESP8266 OS\" device=\"ESP8266 Device using WinTAK COT\"/><contact callsign=\"callsing\" endpoint=\"*:-1:stcp\"/><uid Droid=\"Droid_%d\"/><__group name=\"Red\" role=\"Team Member\"/><status battery=\"69\"/><track course=\"0.00000000\" speed=\"0.00000000\"/></detail></event>", IMEI_NO, TIME, START, STALE, IMEI_NO, IMEI_NO);`

after that the ESP is shown as member on the FTS server but disconnects after a few seconds and is not connecting again as member

**Comment by Cale-Torino** [comment]
Hmmm it's working for me on `FTS 1.9.9` are you using it over LAN or on the actual internet? Port 4242 gets used on LAN for direct private chats. 

If you try trigger the events via public chat it should work. Not sure why the ping is not updating though. If it still doesn't work for you then I'll upload the exact sketch I'm running now

**Comment by DanielHeinze** [comment]
Hi, iam using it via Internet so all traffic should be sent over Port 8087.

I tried triggering callRESTART or Roger over the "All Group Chat" an nothing happended. device is not restarting or internal LED blinkin.

would be nice if you could upload your current running version :)

**Comment by Cale-Torino** [comment]
I added the version I was testing

**Comment by DanielHeinze** [comment]
Thanks. With this version, the esp is showing up as a member after it boots up for a second. 
After one second Shows as offline in atak and if i sent commands via the Group chat nothing happended

**Comment by Cale-Torino** [comment]
I think the device goes to stale so you will have to add the correct date via:
```C++
#define TIME "2022-04-12T13:31:00.000Z"
#define START "2022-04-12T13:31:00.000Z"
#define STALE "2022-04-12T13:31:00.000Z"
```

I will add an auto date function sometime in the future but I am busy with exams at the moment.

Regarding the commands I think the problem is the `msgStr = (char*)data;` variable it needs to use the `(uint8_t*)data` and  `len` variables passed through `handleData(void* arg, AsyncClient* client, void *data, size_t len)` but I could only pass is with reference to the data as a char* using safestrings. The solution may be to use a better TCP library or try find a way to get a string using `(uint8_t*)data` and  `len` but at the moment I have no idea.

It was working for me because I don't have much activity on port `8087` so my string var was able to get the `Roger` and `callRESTART` commands but the length could be anything so it's not a good solution the `msgStr` var must use the `(uint8_t*)data` and  `len` vars to get a reliable string reading. Strings are known to be problems with embedded devices.

I will have to think about it but perhaps in the meantime you could try find a reliable solution?
